# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_cache/vector_store/vector_store.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llm_cache/vector_store/vector_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)llm_cache/vector_store/vector_store.proto\x12\x0bvectorstore\"&\n\x14SearchSimilarRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"_\n\x12SearchSimilarReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\x12\x18\n\x10similarity_score\x18\x04 \x01(\x02\"@\n\x0cStoreRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x0e\n\x06vector\x18\x03 \x03(\x02\"\x1d\n\nStoreReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa6\x01\n\x12VectorStoreService\x12S\n\rSearchSimilar\x12!.vectorstore.SearchSimilarRequest\x1a\x1f.vectorstore.SearchSimilarReply\x12;\n\x05Store\x12\x19.vectorstore.StoreRequest\x1a\x17.vectorstore.StoreReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_cache.vector_store.vector_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHSIMILARREQUEST']._serialized_start=58
  _globals['_SEARCHSIMILARREQUEST']._serialized_end=96
  _globals['_SEARCHSIMILARREPLY']._serialized_start=98
  _globals['_SEARCHSIMILARREPLY']._serialized_end=193
  _globals['_STOREREQUEST']._serialized_start=195
  _globals['_STOREREQUEST']._serialized_end=259
  _globals['_STOREREPLY']._serialized_start=261
  _globals['_STOREREPLY']._serialized_end=290
  _globals['_VECTORSTORESERVICE']._serialized_start=293
  _globals['_VECTORSTORESERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
