# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llm_cache.vector_store import vector_store_pb2 as llm__cache_dot_vector__store_dot_vector__store__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_cache/vector_store/vector_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorStoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchSimilar = channel.unary_unary(
                '/vectorstore.VectorStoreService/SearchSimilar',
                request_serializer=llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarRequest.SerializeToString,
                response_deserializer=llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarReply.FromString,
                _registered_method=True)
        self.Store = channel.unary_unary(
                '/vectorstore.VectorStoreService/Store',
                request_serializer=llm__cache_dot_vector__store_dot_vector__store__pb2.StoreRequest.SerializeToString,
                response_deserializer=llm__cache_dot_vector__store_dot_vector__store__pb2.StoreReply.FromString,
                _registered_method=True)


class VectorStoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SearchSimilar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilar,
                    request_deserializer=llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarRequest.FromString,
                    response_serializer=llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarReply.SerializeToString,
            ),
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=llm__cache_dot_vector__store_dot_vector__store__pb2.StoreRequest.FromString,
                    response_serializer=llm__cache_dot_vector__store_dot_vector__store__pb2.StoreReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectorstore.VectorStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectorstore.VectorStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectorstore.VectorStoreService/SearchSimilar',
            llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarRequest.SerializeToString,
            llm__cache_dot_vector__store_dot_vector__store__pb2.SearchSimilarReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectorstore.VectorStoreService/Store',
            llm__cache_dot_vector__store_dot_vector__store__pb2.StoreRequest.SerializeToString,
            llm__cache_dot_vector__store_dot_vector__store__pb2.StoreReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
