# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_cache/llm/llm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llm_cache/llm/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17llm_cache/llm/llm.proto\x12\x03llm\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"!\n\rGenerateReply\x12\x10\n\x08response\x18\x01 \x01(\t2B\n\nLLMService\x12\x34\n\x08Generate\x12\x14.llm.GenerateRequest\x1a\x12.llm.GenerateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_cache.llm.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=32
  _globals['_GENERATEREQUEST']._serialized_end=65
  _globals['_GENERATEREPLY']._serialized_start=67
  _globals['_GENERATEREPLY']._serialized_end=100
  _globals['_LLMSERVICE']._serialized_start=102
  _globals['_LLMSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
